### ISSUE TITLE
ROADMAP #doli

### ISSUE THREAD

**Issue by odanoburu** [labFGV/DOliberto#36]
- [ ] v0.1 (α)
  - [ ] upload e escrita de tabela (#31)
  - [ ] especializar as forms para cada tipo de ato, capturando
    metadados específicos (#32)
  - [ ] reordenação de atos (#33)
  - [ ] levantar servidor ES (#3, #7)
  - [x] merge servidor e site (#34)

- [ ] v1.0
  - [ ] exportação HTML
  - [ ] autenticação dos usuários de cada secretaria
  - [ ] implementar XML?
  - [ ] *document automation*

- [x] v0.0.1 (α da α, proof of concept)
  - [x] interface web
    - [x] inserção de vários atos em uma edição
    - [x] metadados: título, autor, cargo do autor, secretaria
    - [x] gerar .json com os atos
    - ~[ ] cross-request do frontend para o servidor (#27)~
    - [x] servir js,html,css,python do mesmo servidor, sem precisar de cross-origin request (#27 #34)
  - [x] gerar .pdf a partir do .json (usando pyLaTeX)
    - [x] criar classe LaTeX (`doliberto.cls`)
      - [x] environment de secretaria
      - [x] comando para atos com os metadados existentes
      - [x] header com logo de mesquita
      - [x] formatação semelhante a de um D.O.
    - [x] ordenação dos atos de acordo com a prefeitura de Mesquita (`doli.py`)
  - [x] servidor apache rodando em docker container
    - [x] receber POST com .json e devolver .pdf
    - [x] salvar .json na nuvem (#35)
